---
creation_rules:
  - path_regex: .*\.sops\.ya?ml
    # Personal, VyOS
    age: 
      - age1mzxwncaj0364q8jxfj0y73ptt63czwxucf9lrnn28c7kwyr5wfdsj9gsk2
      - age13h8je8c8jjuspfax26hp3tecs0gugws533t3xxrmn2n3tjuu8e5q5ha2r4
